### ISSUE TITLE
Router设计

### ISSUE THREAD

**Issue by imishx** [70kg/70kg.github.io#2]
A携带参数跳到B，给B配一个Login拦截器，所有跳到B的都需要先在拦截器判断登陆，登陆成功之后如何在跳到B呢，参数如何传递呢
代码呢？

**Comment by 70kg** [comment]
首先登录拦截器是全局的，并不是给某个页面单独设置，某个页面需不需要登录是确定的，如果需要登录就在 自己的`switcher` 中设置 `needLogin` 为 `true`,这样路由就对自动引导到登录页面，同时保留之前的参数。登录页面是一个固定的页面，登录成功之后无论是使用回调还是类似`` `EventBus` 的库都可以完成。登录成功传递的参数就是之前的参数，原封不变。

``` java
public class LoginInterceptor implements Interceptor {

    @Override
    public void intercept(NavigationManager navigationManager, Switcher switcher, Chain chain) {
        if (switcher instanceof FragmentSwitcher) {
            if (((FragmentSwitcher) switcher).needLogin()) {
                chain.setIntercepted(true);
                handleLogin(navigationManager, (FragmentSwitcher) switcher, chain);
            }
        }
    }

    private void handleLogin(NavigationManager navigationManager, FragmentSwitcher switcher, Chain chain) {
        if (!UserManager.getInstance().isLogin()) {
                LoginDialogFragment loginDialogFragment = LoginDialogFragment.newInstance(0,
                        (isLogin, isRegister) -> {
                            if (isLogin) {
                                switcher.switchTo(navigationManager, chain.uri, chain.bundle);
                            }
                        });
                if (!loginDialogFragment.isAdded()) {
                    loginDialogFragment.show(navigationManager.getFragmentManager(), "LoginDialogFragment");
                }
       }else {
            switcher.switchTo(navigationManager, chain.uri, chain.bundle);
        }
}
```
因为用在公司项目中，暂不开源，而且框架暂时只适配单 `Activity` + `Fragments` 的结构，目前使用的似乎并不多。所以没有开源，但是整个思路已经开源出来，写起来应该难度不大。有兴趣可以反编译一下波罗蜜apk。因为一些原因还没混淆，很简单。谢谢

**Comment by imishx** [comment]
很感谢你的回答，我最近真对我们项目也在设计一个路由框架，可能跟你的不一样，我的是多Activity界面，我说说我的想法：
1、关于拦截器的设置我觉得应该针对页面比较好一些，真对不同的页面拦截的逻辑可能不一样，除了登陆拦截可能还有其它拦截，拦截器里面的判断逻辑也可能同步也可能异步。
2、参数传递问题，A界面想跳到B界面并传一个参数，可能被拦截之后中间周转了很多界面，参数肯定不能在中间这些界面一直传递。
3、经过一系列拦截之后如何确保路由到正确的界面

**Comment by 70kg** [comment]
1:我已经对每个页面抽象出一个 `switcher` ,在这里足够做一些处理。不同页面拦截的逻辑不一样，你可以去实现多个拦截器，然后加入到路由中。
2：参数肯定不会在这么界面之间传递，一直被第一个拦截器持有，等结果返回的时候再去传递到目标页面。
3:同2。

ps :我去申请一下开源，然后去适配一下 `activity` 的模式。谢谢关注
